path_classifiers:
   test: "$GNU_MAKE test"
   docs: "$GNU_MAKE doc"
extraction:
  cpp:
    prepare:
      packages:
      - "gcc"
      - "libtool"
      - "autoconf-archive"
      - "libglib2.0-dev"
      - "doxygen"
      - "graphviz"
      - "markdown"
      - "python3-cram"
      - "handbrake-cli"
    after_prepare: "export GNU_MAKE=make"
    configure:
      command:
      - "./autogen.sh"
      - "./configure"
    index:
      build_command: "$GNU_MAKE -j2"
