language: c

matrix:
    include:
        compiler:
            - clang
            - gcc
        - name: "Base"
          addons:
              apt:
                  packages:
                      - libglib2.0-dev
        - name: "Base + Doxygen"
          addons:
              apt:
                  packages:
                      - libglib2.0-dev
                      - doxygen
                      - graphviz
                      - markdown
          script: ./configure && make && make doc && make test

before_script: ./autogen.sh

install: true
