language: c

matrix:
    include:
        - name: "Base"
          compiler:
              - clang
              - gcc
          addons:
              apt:
                  packages:
                      - libglib2.0-dev
        - name: "Base + Doxygen"
          compiler:
              - clang
              - gcc
          addons:
              apt:
                  packages:
                      - libglib2.0-dev
                      - doxygen
                      - graphviz
                      - markdown
          script: ./configure && make && make doc && make test

before_script: ./autogen.sh

install: true
