language: c
dist: xenial
addons:
    apt:
        packages:
            - libtool
            - autoconf-archive
            - libglib2.0-dev
            - doxygen
            - graphviz
            - markdown
            - python3-cram

compiler:
    - clang
    - gcc

matrix:
    include:
        - name: "Build Doxygen docs"
          script: ./configure && make && make doc && make test

before_script: ./autogen.sh

install: true
