language: c

compiler:
    - clang
    - gcc

matrix:
    include:
        - name: "Build Doxygen docs"
          dist: xenial
          addons:
              apt:
                  packages:
                      - libtool
                      - autoconf-archive
                      - libglib2.0-dev
                      - doxygen
                      - graphviz
                      - markdown
          script: ./configure && make && make doc && make test

before_script: ./autogen.sh

install: true
