language: c

compiler:
    - clang
    - gcc

matrix:
    include:
        - name: "Base"
            addons:
                apt:
                    packages:
                        - libglib2.0-dev
        - name: "Base + Doxygen"
            addons:
                apt:
                    packages:
                        - libglib2.0-dev
                        - doxygen
                        - graphviz
                        - markdown

before_script: ./autogen.sh

install: true
